import type { Metadata } from "next";
import { Inter } from "next/font/google";
import StyledComponentsRegistry from "@/lib/antd.registry";
import "./globals.css";
import LayoutWrapper from "@/lib/layout.wrapper";
import NextAuthWrapper from "@/lib/next.auth.wrapper";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <NextAuthWrapper>
            <Header />
            {children}
          </NextAuthWrapper>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
